"use client";
import { useEffect, useState } from "react";
import { signOut } from "next-auth/react";
import { PageHeader, Section } from "@/components/ui";
import { Icon } from "@/components/icons";

type SettingsState={name:string;email:string;timezone:string;walkingTargetSteps:number;waterTargetMl:number;sleepTargetHours:number;reminderHour:number;emailDailyReminder:boolean;emailMissedDay:boolean;emailThirtyDayReport:boolean;emailLevelUp:boolean;emailCertificateUnlock:boolean;sundayWalkingMode:"WALK"|"REST";workoutSchedule:Record<string,string>};
export default function Settings(){
 const [data,setData]=useState<SettingsState|null>(null); const [error,setError]=useState(""); const [saving,setSaving]=useState(false); const [saved,setSaved]=useState(false); const [deleting,setDeleting]=useState(false);
 useEffect(()=>{fetch("/api/settings",{cache:"no-store"}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error);setData({name:j.name,email:j.email,...j.settings})}).catch(e=>setError(e.message||"Unable to load settings"));},[]);
 if(!data)return <div className="mx-auto max-w-[1100px] px-4 py-10"><div className="panel p-8 text-sm text-[#8C8880]">{error||"Loading settings…"}</div></div>;
 const set=(key:keyof SettingsState,value:any)=>setData(d=>d?({...d,[key]:value}):d);
 async function save(){setSaving(true);setError("");const {name,email,workoutSchedule,...settings}=data;const r=await fetch("/api/settings",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,settings})});const j=await r.json();if(!r.ok){setError(j.error||"Unable to save settings");setSaving(false);return;}setData({name:j.name,email:j.email,...j.settings});setSaved(true);setSaving(false);setTimeout(()=>setSaved(false),1800);}
 async function exportData(){window.location.assign("/api/export");}
 async function deleteAccount(){const password=window.prompt("Enter your account password to permanently delete your account.");if(password===null)return;setDeleting(true);setError("");const r=await fetch("/api/account/delete",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password})});const j=await r.json().catch(()=>({}));if(!r.ok){setError(j.error||"Unable to delete account");setDeleting(false);return;}window.location.assign("/login");}
 return <div className="mx-auto max-w-[1100px] px-4 py-7 sm:px-6 lg:px-10 lg:py-10"><PageHeader eyebrow="Settings" title="Tune the system." description="These controls are persisted to your account and used by the daily engine."/><div className="space-y-4">{error&&<div className="rounded-lg border border-red-300/20 bg-red-300/5 p-3 text-xs text-red-200">{error}</div>}
 <Section title="Daily targets" meta="saved to your account"><div className="grid gap-5 p-5 sm:grid-cols-3"><Field label="Step target" value={data.walkingTargetSteps} set={v=>set("walkingTargetSteps",v)} suffix="steps"/><Field label="Water target" value={data.waterTargetMl} set={v=>set("waterTargetMl",v)} suffix="ml"/><Field label="Sleep target" value={data.sleepTargetHours} set={v=>set("sleepTargetHours",v)} suffix="hours"/></div></Section>
 <Section title="Profile & time"><div className="grid gap-5 p-5 sm:grid-cols-2"><TextField label="Display name" value={data.name} set={v=>set("name",v)}/><label className="block"><span className="text-xs text-[#8C8880]">Timezone</span><select value={data.timezone} onChange={e=>set("timezone",e.target.value)} className="focus-ring mt-2 w-full rounded-lg border border-white/10 bg-[#111111] px-3 py-3 text-sm outline-none"><option>Asia/Dhaka</option><option>UTC</option><option>Asia/Kolkata</option><option>Europe/London</option><option>America/New_York</option></select></label><Field label="Reminder hour" value={data.reminderHour} set={v=>set("reminderHour",v)} suffix="local hour"/><div><span className="text-xs text-[#8C8880]">Email</span><div className="mt-2 rounded-lg border border-white/10 px-3 py-3 text-sm text-[#8C8880]">{data.email}</div></div></div></Section>
 <Section title="Sunday walking" meta="daily rule"><div className="p-5"><div className="grid gap-3 sm:grid-cols-2"><Choice active={data.sundayWalkingMode==="WALK"} title="Walk" description="Walking remains an applicable Sunday task." onClick={()=>set("sundayWalkingMode","WALK")}/><Choice active={data.sundayWalkingMode==="REST"} title="Rest" description="Walking becomes planned rest and is excluded from the score." onClick={()=>set("sundayWalkingMode","REST")}/></div></div></Section>
 <Section title="Reminders & email"><div className="grid gap-3 p-5 sm:grid-cols-2"><Toggle label="Daily reminder" value={data.emailDailyReminder} set={v=>set("emailDailyReminder",v)}/><Toggle label="Missed-day reminder" value={data.emailMissedDay} set={v=>set("emailMissedDay",v)}/><Toggle label="30-day report" value={data.emailThirtyDayReport} set={v=>set("emailThirtyDayReport",v)}/><Toggle label="Level-up email" value={data.emailLevelUp} set={v=>set("emailLevelUp",v)}/><Toggle label="Certificate unlock" value={data.emailCertificateUnlock} set={v=>set("emailCertificateUnlock",v)}/></div></Section>
 <Section title="Workout schedule"><div className="grid gap-2 p-5 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(data.workoutSchedule).map(([day,value])=><div key={day} className="rounded-lg border border-white/10 px-3 py-3 text-xs text-[#8C8880]"><span className="text-[#FAF9F6]">{day}</span><span className="ml-2">· {value}</span></div>)}</div><div className="px-5 pb-5 text-[11px] text-[#6f6b65]">The training schedule is the saved challenge rule. Sunday walking is controlled separately above.</div></Section>
 <Section title="Account & data"><div className="grid gap-3 p-5 sm:grid-cols-2"><button onClick={exportData} className="focus-ring flex items-center justify-between rounded-lg border border-white/10 px-4 py-3 text-sm text-[#8C8880] hover:text-[#FAF9F6]"><span>Export data</span><Icon.Download size={16}/></button><button onClick={()=>signOut({callbackUrl:"/login"})} className="focus-ring flex items-center justify-between rounded-lg border border-white/10 px-4 py-3 text-sm text-[#8C8880] hover:text-[#FAF9F6]"><span>Sign out</span><Icon.LogOut size={16}/></button><button disabled={deleting} onClick={deleteAccount} className="focus-ring flex items-center justify-between rounded-lg border border-red-300/20 px-4 py-3 text-sm text-red-200 hover:bg-red-300/5 disabled:opacity-50"><span>{deleting?"Deleting…":"Delete account"}</span><Icon.Trash2 size={16}/></button></div></Section>
 <div className="flex items-center justify-between rounded-xl border border-white/10 bg-white/[.02] p-4"><span className="text-xs text-[#8C8880]">{saved?"Saved to your account.":"Changes are saved only when you press Save changes."}</span><button onClick={save} disabled={saving} className="focus-ring flex items-center gap-2 rounded-lg bg-[#C9A574] px-4 py-2.5 text-xs font-semibold text-[#111111] disabled:opacity-60"><Icon.Save size={15}/>{saving?"Saving…":saved?"Saved":"Save changes"}</button></div></div></div>
}
function Field({label,value,set,suffix}:{label:string;value:number;set:(v:number)=>void;suffix:string}){return <label className="block"><span className="text-xs text-[#8C8880]">{label}</span><div className="mt-2 flex items-center rounded-lg border border-white/10 bg-[#111111]"><input type="number" min={0} value={value} onChange={e=>set(Number(e.target.value))} className="focus-ring w-full bg-transparent px-3 py-3 text-sm outline-none"/><span className="pr-3 text-[11px] text-[#6f6b65]">{suffix}</span></div></label>}
function TextField({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <label className="block"><span className="text-xs text-[#8C8880]">{label}</span><input value={value} onChange={e=>set(e.target.value)} className="focus-ring mt-2 w-full rounded-lg border border-white/10 bg-[#111111] px-3 py-3 text-sm outline-none"/></label>}
function Toggle({label,value,set}:{label:string;value:boolean;set:(v:boolean)=>void}){return <button type="button" onClick={()=>set(!value)} className="focus-ring flex items-center justify-between rounded-lg border border-white/10 px-4 py-3 text-left"><span className="text-sm">{label}</span><span className={`h-5 w-9 rounded-full p-0.5 ${value?"bg-[#C9A574]":"bg-white/10"}`}><span className={`block h-4 w-4 rounded-full bg-[#111111] transition ${value?"translate-x-4":""}`}/></span></button>}
function Choice({active,title,description,onClick}:{active:boolean;title:string;description:string;onClick:()=>void}){return <button type="button" onClick={onClick} className={`focus-ring rounded-lg border p-4 text-left ${active?"border-[#C9A574]/40 bg-[#C9A574]/5":"border-white/10"}`}><div className="text-sm font-medium">{title}</div><div className="mt-1 text-xs leading-5 text-[#8C8880]">{description}</div></button>}
