"use client";
import { useEffect, useState } from "react";
import { PageHeader, ProgressBar, Section } from "@/components/ui";
import { Icon } from "@/components/icons";
export default function Certificate(){
 const [data,setData]=useState<any>(null); const [error,setError]=useState("");
 useEffect(()=>{fetch("/api/certificate",{cache:"no-store"}).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error);setData(j)}).catch(e=>setError(e.message||"Unable to load certificate"));},[]);
 if(!data) return <div className="mx-auto max-w-[1100px] px-4 py-10"><div className="panel p-8 text-sm text-[#8C8880]">{error||"Loading certificate…"}</div></div>;
 const pct=Math.round(data.progressPercent); const unlocked=Boolean(data.certificateUnlocked); const achievement=data.achievement;
 return <div className="mx-auto max-w-[1100px] px-4 py-7 sm:px-6 lg:px-10 lg:py-10"><PageHeader eyebrow="Certificate" title="Earn the proof." description="A personal achievement certificate unlocked at 600 net tokens. It is not official accreditation."/><div className="panel overflow-hidden"><div className="grid-fade p-7 sm:p-12"><div className="mx-auto max-w-2xl text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full border border-[#C9A574]/30 bg-[#C9A574]/10 text-[#C9A574]">{unlocked?<Icon.Trophy size={22}/>:<Icon.LockKeyhole size={22}/>}</div><div className="mt-6 text-[10px] font-bold uppercase tracking-[.28em] text-[#C9A574]">Achievement certificate</div><h2 className="mt-3 text-3xl font-semibold">{unlocked?"Comeback complete.":"Comeback in progress."}</h2><p className="mx-auto mt-3 max-w-md text-sm leading-6 text-[#8C8880]">{unlocked?"Your account has reached the 600 net-token threshold.":"Reach 600 net tokens to unlock your personal certificate."}</p><div className="mt-8"><ProgressBar value={pct}/><div className="mt-3 flex justify-between text-xs text-[#8C8880]"><span>{data.netTokens} net tokens</span><span>{Math.max(0,600-data.netTokens)} remaining</span></div></div><div className="mt-8 grid gap-3 text-left sm:grid-cols-3"><Mini label="Current level" value={data.level}/><Mini label="Target" value="600 tokens"/><Mini label="Certificate" value={unlocked?"Unlocked":"Locked"}/></div></div></div><div className="border-t border-white/10 p-5 text-center text-xs text-[#6f6b65]">{unlocked?`Unlocked ${achievement?.unlockedAt ? new Date(achievement.unlockedAt).toLocaleDateString() : ""}`:"Download becomes available when the unlock threshold is reached."}</div></div><div className="mt-4 flex justify-center">{unlocked&&<button onClick={()=>window.location.assign("/api/certificate/pdf")} className="rounded-lg bg-[#C9A574] px-4 py-2.5 text-xs font-semibold text-[#111111]">Download certificate</button>}</div><Section title="When unlocked" className="mt-4"><div className="grid gap-4 p-5 sm:grid-cols-2"><Mini label="Name" value={data.name}/><Mini label="Achievement" value="Comeback Complete"/><Mini label="Completion date" value={achievement?.unlockedAt?new Date(achievement.unlockedAt).toLocaleDateString():"Displayed at unlock"}/><Mini label="Certificate ID" value={achievement?.id??"Generated at unlock"}/></div></Section></div>
}
function Mini({label,value}:{label:string;value:string}){return <div className="rounded-lg border border-white/10 p-4"><div className="text-[10px] uppercase tracking-[.14em] text-[#8C8880]">{label}</div><div className="mt-2 text-sm font-medium">{value}</div></div>}
